---
title: "29RTGRaw"
output: pdf_document
---


```{r setup, include=FALSE}
library(tidyverse)
library(knitr)
```

# Raw data set
Letter "m" = "same", letter "n" = "different".

For P2: two first datasets = 268 stimuli rows with S (start), one break and 6 practica. L3&L4 = 392 stimuli rows (respectively) with S, 1 break, and 2 practice (LAST ONE DIDN'T FINISHED)

```{r}
#Raw with no practice, no S, and no break

RawDataSet1 <- list.files(pattern = "xP20_") %>%
  lapply(read_csv) %>% 
  bind_rows%>%
  mutate(Subject= rep(list.files(pattern = "xP20_"), each=268))%>%
  separate(`IT1 IT2 KEY RT`,c("IT1","a", "IT2","b","c","d","e","f","g","KEY", "RT"), sep = " ")%>%
  select(Subject,IT1,IT2,KEY,RT)%>%
  filter(IT1 != "S",
         IT1 !="DESCANSO")%>%
  mutate(Rubric = if_else(IT1 ==IT2, "m", "n"),
         Accuracy = if_else(KEY == Rubric, 1, 0),
         RT = as.numeric(RT))%>%
  group_by(Subject)%>%
  slice(7:266)%>%
  ungroup()

RawDataSet2 <- read_csv("yP20_RTG_3") %>%
  mutate(Subject= rep(list.files(pattern = "yP20_RTG_3"), 396))%>%
  separate(`IT1 IT2 KEY RT`,c("IT1","a", "IT2","b","c","d","e","f","g","KEY", "RT"), sep = " ")%>%
  select(Subject,IT1,IT2,KEY,RT)%>%
  filter(IT1 != "S",
         IT1 !="DESCANSO")%>%
  mutate(Rubric = if_else(IT1 ==IT2, "m", "n"),
         Accuracy = if_else(KEY == Rubric, 1, 0),
         RT = as.numeric(RT))%>%
   slice(3:394)

RawDataSet3 <- read_csv("yP20_RTG_4") %>%
  mutate(Subject= rep(list.files(pattern = "yP20_RTG_4"), 330))%>%
  separate(`IT1 IT2 KEY RT`,c("IT1","a", "IT2","b","c","d","e","f","g","KEY", "RT"), sep = " ")%>%
  select(Subject,IT1,IT2,KEY,RT)%>%
  filter(IT1 != "S",
         IT1 !="DESCANSO")%>%
  mutate(Rubric = if_else(IT1 ==IT2, "m", "n"),
         Accuracy = if_else(KEY == Rubric, 1, 0),
         RT = as.numeric(RT))%>%
   slice(3:328)

P20RTGRaw<-RawDataSet1%>%
  bind_rows(RawDataSet2,RawDataSet3)

save(P20RTGRaw, file = "P20RTGRaw.RData")
  
```
  
  